pipeline {
    agent any
    stages {
        stage('docker run MySQL image') {
             steps {
                 sh "docker run --name my_movie_plan1 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=my_movie_plan1 -e MYSQL_USER=root -e MYSQL_PASSWORD=root -d mysql:latest"
             }
        }

        stage('docker images') {
             steps {
                 sh "docker images"
             }
        }
    }
}